version: '3.8'

services:

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: jenkins
      POSTGRES_PASSWORD: jenkins
      POSTGRES_DB: jenkins-data
    volumes:
      - db-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jenkins -d jenkins-data"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: always
    ports:
      - "9090:9090"
    environment:
      DATABASE_URL: "postgres://jenkins:jenkins@db:5432/jenkins-data?sslmode=disable"
      JENKINS_URL: "https://finops-jenkins.ck.tothenew.net/"
      JENKINS_USER: "amol.pandey@cloudkeeper.com"      # <-- Change this!
      JENKINS_TOKEN: "1162ccb5f90ca6584d6ecb180a3626bc54" # <-- Change this!
    

    extra_hosts:
      - "host.docker.internal:host-gateway"
      

    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data: